[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --strict-markers
    --strict-config
    --cov=app
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-report=xml
    --tb=short
markers =
    unit: Unit tests
    integration: Integration tests
    slow: Slow running tests
    database: Tests that require database connection
    sheets: Tests that involve Google Sheets
env = 
    TESTING=true
    DB_HOST=localhost
    DB_PORT=5432
    DB_NAME=test_db
    DB_USER=test_user
    DB_PASSWORD=test_password
pythonpath = .